"""Service generating printable and downloadable Attorney Prep Briefs in Markdown and HTML format."""

from datetime import datetime
from app.models.analysis import DocumentAnalysisResponse
from app.models.lawyer_brief import LawyerPrepBrief, AttorneyConsultationQuestion


class BriefExportService:
    """Generates a structured, one-page attorney preparation dossier."""

    @classmethod
    def generate_brief(cls, doc_name: str, analysis: DocumentAnalysisResponse) -> LawyerPrepBrief:
        """Assembles the structured lawyer prep brief from the document intelligence pass."""
        questions = []
        for flag in analysis.risk_flags[:5]:
            questions.append(AttorneyConsultationQuestion(
                category="Risk Mitigation",
                question=f"Regarding '{flag.title}' ({flag.clause_reference}): Is this standard practice in this jurisdiction, or can we strike or negotiate this term?",
                context_clause=flag.verbatim_text[:140] + "...",
                why_to_ask=f"Because: {flag.why_it_matters}"
            ))

        # Add general strategic question
        questions.append(AttorneyConsultationQuestion(
            category="Dispute Resolution",
            question="If a breach or dispute occurs, does this agreement limit my legal recourse or force me into costly arbitration?",
            context_clause="Dispute Resolution & Governing Law provisions",
            why_to_ask="Arbitration and fee-shifting clauses can prevent you from defending your rights in small claims court."
        ))

        docs_to_bring = [
            f"The complete signed or proposed copy of {doc_name}",
            "Any prior versions or addenda exchanged with the other party",
            "Written correspondence (emails, text messages, letters) discussing negotiated terms",
            "Proof of payments, deposits, or fee receipts already exchanged",
            "A government-issued ID and contact details for all parties"
        ]

        timelines = [
            "Review deadline: Consult counsel before signing or within the statutory cooling-off window",
            "Notice periods: Flagged clauses may require 30 to 60 days advance written notice for termination",
            "Cure periods: Check if you have at least 10–14 days to cure any alleged default before penalties accrue"
        ]

        return LawyerPrepBrief(
            document_id=analysis.document_id,
            document_name=doc_name,
            document_type=analysis.document_type,
            generated_date=datetime.utcnow().strftime("%B %d, %Y"),
            executive_summary=analysis.plain_summary,
            critical_concerns=analysis.risk_flags[:6],
            recommended_questions=questions,
            documents_to_bring=docs_to_bring,
            timeline_and_deadlines=timelines
        )

    @classmethod
    def render_markdown(cls, brief: LawyerPrepBrief) -> str:
        """Renders the brief as clean, professional GitHub-flavored Markdown."""
        lines = [
            f"# Attorney Consultation Brief: {brief.document_name}",
            f"**Document Type**: {brief.document_type} | **Prepared Date**: {brief.generated_date}",
            "",
            "> **NOTICE**: " + brief.disclaimer,
            "",
            "## 1. Executive Summary & Plain-Language Context",
            brief.executive_summary,
            "",
            "## 2. Priority Risk Flags & Problematic Clauses Identified",
        ]

        for flag in brief.critical_concerns:
            lines.append(f"### [{flag.severity.upper()}] {flag.title} ({flag.clause_reference})")
            lines.append(f"- **Verbatim Text**: *\"{flag.verbatim_text}\"*")
            lines.append(f"- **Plain Explanation**: {flag.plain_explanation}")
            lines.append(f"- **Why This Matters**: {flag.why_it_matters}")
            lines.append(f"- **Who It Favors**: {flag.who_it_favors}")
            lines.append("")

        lines.extend([
            "## 3. Targeted Questions to Ask Your Attorney",
            "Maximize your legal consultation efficiency by asking these specific questions:",
        ])
        for q in brief.recommended_questions:
            lines.append(f"- **[{q.category}]** {q.question}")
            lines.append(f"  *Reasoning*: {q.why_to_ask}")

        lines.extend([
            "",
            "## 4. Checklist: Documents & Evidence to Bring",
        ])
        for doc in brief.documents_to_bring:
            lines.append(f"- [ ] {doc}")

        lines.extend([
            "",
            "## 5. Critical Timelines & Deadlines",
        ])
        for t in brief.timeline_and_deadlines:
            lines.append(f"- ⏳ {t}")

        lines.extend([
            "",
            "---",
            "*Generated by LegalEase — Democratizing Legal Comprehension for Everyday Users.*"
        ])
        return "\n".join(lines)
